openapi: 3.0.0

tags:
  - material
components:
  schemas:
    Material:
      type: object
      properties:
        company_id:
          type: integer
        brandType:
          type: string
        brandName:
          type: string
        unitPrice:
          type: number
        description:
          type: string
        sku:
          type: string
      example:
        company_id: 1
        brandType: AAA
        brandName: United Beverage
        unitPrice: 23.4
        description: Product description
        sku: sku 

paths:
  /api/v1.0/materials:
    get:
      summary: Gets all list of Materials
      description: Fetches all list of Materials registered in the database
      tags:
        - material
      responses:
        '200':
          description: successful fetch
          content:
            application/json:
              properties:
                material:
                  type: array
        '401':
          description: Access Denied
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal server error
          content:
            application/json:
              properties:
                msg:
                  type: string

    post: 
      summary: fetch new material data to db
      description: used to fetch new material data to db
      tags:
        - material
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Material"
      responses:
        '201':
          description: Sccessful fetch 
          content:
            application/json:
              properties:
                material:
                  type: array 
        '400':
          description: BAD DATA
          content:
            application/json:
              properties:
                msg:
                  type: string 
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string 

  /api/v1.0/materials/{id}:
    get:
      summary: Fetch a specific material 
      description: Fetch a specific material relative to the specified id
      tags:
        - material
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric id of the material
      responses:
        '200':
          description: Successfuly loaded
          content:
            application/json:
              properties:
                material:
                  type: object
        '400':
          descriprion: Bad Data
          content:
            application/json:
              properties:
                msg:
                  type: string
        '404':
          description: material Not Found
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string
    patch:
      summary: Edit material
      description: Edit material relative to user
      tags:
        - material
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric identifier of the material
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Material'
      responses:
        '200':
          description: Successfuly Edited material
          content:
            application/json:
              properties:
                material:
                  type: object
        '400':
          description: Bad Data
          content:
            application/json:
              properties:
                msg:
                  type: string
        '404':
          description: material Not Found
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string
    delete:
      summary: Delete material
      description: soft delete material from db
      tags:
        - material
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric identifier of material
      responses:
        '200':
          description: material with the id is deleted successfully
          content:
            application/json:
              msg:  
                type: string
        '404':
          description: material with the specified id is not found
          content:
            application/json:
              msg:  
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              msg:  
                type: string

