openapi: 3.0.0

tags:
  - nation
components:
  schemas:
    Nation:
      type: object
      properties:
        nationCode:
          type: string
        nationName:
          type: string
      example:
        nationCode: ET
        nationName: Ethiopia

paths:
  /api/v1.0/nations:
    get:
      summary: Gets all list of nations
      description: Fetches all list of nations registered in the database
      tags:
        - nation
      responses:
        '200':
          description: successful fetch
          content:
            application/json:
              properties:
                nation:
                  type: array
        '401':
          description: Access Denied
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal server error
          content:
            application/json:
              properties:
                msg:
                  type: string

    post: 
      summary: fetch new nation data to db
      description: used to fetch new nation data to db
      tags:
        - nation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Nation"
      responses:
        '201':
          description: Sccessful fetch 
          content:
            application/json:
              properties:
                nation:
                  type: array 
        '400':
          description: BAD DATA
          content:
            application/json:
              properties:
                msg:
                  type: string 
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string 

  /api/v1.0/nations/{id}:
    get:
      summary: Fetch a specific nation 
      description: Fetch a specific nation relative to the specified id
      tags:
        - nation
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric id of the nation
      responses:
        '200':
          description: Successfuly loaded
          content:
            application/json:
              properties:
                nation:
                  type: object
        '400':
          descriprion: Bad Data
          content:
            application/json:
              properties:
                msg:
                  type: string
        '404':
          description: Nation Not Found
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string
    patch:
      summary: Edit Nation
      description: Edit nation relative to user
      tags:
        - nation
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric identifier of the nation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nation'
      responses:
        '200':
          description: Successfuly Edited Nation
          content:
            application/json:
              properties:
                nation:
                  type: object
        '400':
          description: Bad Data
          content:
            application/json:
              properties:
                msg:
                  type: string
        '404':
          description: Nation Not Found
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string
    delete:
      summary: Delete Nation
      description: soft delete Nation from db
      tags:
        - nation
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric identifier of nation
      responses:
        '200':
          description: nation with the id is deleted successfully
          content:
            application/json:
              msg:  
                type: string
        '404':
          description: nation with the specified id is not found
          content:
            application/json:
              msg:  
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              msg:  
                type: string
