openapi: 3.0.0

tags:
  - territory
components:
  schemas:
    Territory:
      type: object
      properties:
        region_id:
          type: integer
        territoryCode:
          type: string
        territoryName:
          type: string
      example:
        region_id: 1
        territoryCode: AA
        territoryName: Addis Ababa

paths:
  /api/v1.0/territories:
    get:
      summary: Gets all list of trucks
      description: Fetches all list of trucks registered in the database
      tags:
        - territory
      responses:
        '200':
          description: successful fetch
          content:
            application/json:
              properties:
                territory:
                  type: array
        '401':
          description: Access Denied
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal server error
          content:
            application/json:
              properties:
                msg:
                  type: string

    post: 
      summary: fetch new territory data to db
      description: used to fetch new territory data to db
      tags:
        - territory
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Territory"
      responses:
        '201':
          description: Sccessful fetch 
          content:
            application/json:
              properties:
                territory:
                  type: array 
        '400':
          description: BAD DATA
          content:
            application/json:
              properties:
                msg:
                  type: string 
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string 

  /api/v1.0/territories/{id}:
    get:
      summary: Fetch a specific territory 
      description: Fetch a specific territory relative to the specified id
      tags:
        - territory
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric id of the territory
      responses:
        '200':
          description: Successfuly loaded
          content:
            application/json:
              properties:
                territory:
                  type: object
        '400':
          descriprion: Bad Data
          content:
            application/json:
              properties:
                msg:
                  type: string
        '404':
          description: territory Not Found
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string
    patch:
      summary: Edit territory
      description: Edit territory relative to user
      tags:
        - territory
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric identifier of the territory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Territory'
      responses:
        '200':
          description: Successfuly Edited territory
          content:
            application/json:
              properties:
                territory:
                  type: object
        '400':
          description: Bad Data
          content:
            application/json:
              properties:
                msg:
                  type: string
        '404':
          description: territory Not Found
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string
    delete:
      summary: Delete territory
      description: soft delete territory from db
      tags:
        - territory
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric identifier of territory
      responses:
        '200':
          description: territory with the id is deleted successfully
          content:
            application/json:
              msg:  
                type: string
        '404':
          description: territory with the specified id is not found
          content:
            application/json:
              msg:  
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              msg:  
                type: string

