openapi: 3.0.0

tags:
  - truck
components:
  schemas:
    Truck:
      type: object
      properties:
        territory_id:
          type: integer
        truckCode:
          type: string
        truckName:
          type: string
        plateNumber:
          type: string
      example:
        territory_id: 1
        truckCode: AA
        truckName: Isuzu
        plateNumber: '3-23456'

paths:
  /api/v1.0/trucks:
    get:
      summary: Gets all list of trucks
      description: Fetches all list of trucks registered in the database
      tags:
        - truck
      responses:
        '200':
          description: successful fetch
          content:
            application/json:
              properties:
                truck:
                  type: array
        '401':
          description: Access Denied
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal server error
          content:
            application/json:
              properties:
                msg:
                  type: string

    post: 
      summary: fetch new truck data to db
      description: used to fetch new truck data to db
      tags:
        - truck
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Truck"
      responses:
        '201':
          description: Sccessful fetch 
          content:
            application/json:
              properties:
                truck:
                  type: array 
        '400':
          description: BAD DATA
          content:
            application/json:
              properties:
                msg:
                  type: string 
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string 

  /api/v1.0/trucks/{id}:
    get:
      summary: Fetch a specific truck 
      description: Fetch a specific truck relative to the specified id
      tags:
        - truck
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric id of the truck
      responses:
        '200':
          description: Successfuly loaded
          content:
            application/json:
              properties:
                truck:
                  type: object
        '400':
          descriprion: Bad Data
          content:
            application/json:
              properties:
                msg:
                  type: string
        '404':
          description: truck Not Found
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string
    patch:
      summary: Edit truck
      description: Edit truck relative to user
      tags:
        - truck
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric identifier of the truck
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Truck'
      responses:
        '200':
          description: Successfuly Edited truck
          content:
            application/json:
              properties:
                truck:
                  type: object
        '400':
          description: Bad Data
          content:
            application/json:
              properties:
                msg:
                  type: string
        '404':
          description: truck Not Found
          content:
            application/json:
              properties:
                msg:
                  type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              properties:
                msg:
                  type: string
    delete:
      summary: Delete truck
      description: soft delete truck from db
      tags:
        - truck
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: Numeric identifier of truck
      responses:
        '200':
          description: truck with the id is deleted successfully
          content:
            application/json:
              msg:  
                type: string
        '404':
          description: truck with the specified id is not found
          content:
            application/json:
              msg:  
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              msg:  
                type: string

