GET http://localhost:3000/api/v1.0/regions/
Content-Type: application/json 

{
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}

###
GET http://localhost:3000/api/v1.0/regions/1
Content-Type: application/json 

{
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}

### 
POST http://localhost:3000/api/v1.0/regions/
Content-Type: application/json 

{
    "company_id": 1,
    "regionCode": "BDR",
    "regionName": "Bahir Dar",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}


###
PATCH http://localhost:3000/api/v1.0/regions/6
Content-Type: application/json 

{
    "company_id": 1,
    "regionCode": "UB",
    "regionName": "United Beverage",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}

###
DELETE http://localhost:3000/api/v1.0/regions/6
Content-Type: application/json 

{
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}

