GET http://localhost:3000/api/v1.0/routes/
Content-Type: application/json 

{
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}

###
GET http://localhost:4000/api/v1.0/routes/25
Content-Type: application/json 

{
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}

### 
POST http://localhost:3000/api/v1.0/routes/
Content-Type: application/json 

{
    "truck_id": 1,
    "routeCode": "BDR",
    "routeName": "Bahir Dar",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}


###
PATCH http://localhost:3000/api/v1.0/outlets/1
Content-Type: application/json 

{
    "company_id": 1,
    "ownerName": "SFA TEST TEAM",
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}

###
DELETE http://localhost:3000/api/v1.0/route/3
Content-Type: application/json 

{
    "token": "eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwic3RhdHVzX2NvbnRyb2wiOjAsImNyZWF0ZWREYXRlIjoiMjAyMS0xMi0xNlQxMzoxOTozMS4xNDFaIiwibGFzdE1vZGlmaWVkIjoiMjAyMS0xMi0xNlQxMzoxOTozMS41OTNaIiwiZmlyc3ROYW1lIjoidF9mbmFtZSIsIm1pZGRsZU5hbWUiOiJ0X21uYW1lIiwibGFzdE5hbWUiOiJ0X2xuYW1lIiwiZW1haWwiOiJ0ZXN0QGVtYWlsLmNvbSIsInBob25lTnVtYmVyIjoiMDkxMjM0NTA3OCIsInJvbGUiOjEsImFkZHJlc3MiOiJ0ZXN0IGFkZHJlc3MiLCJwb3NpdGlvbiI6InRlc3QgcG9zaXRpb24iLCJwYXNzd29yZCI6IiQyYiQxMCRITjY5M3guaHVMQUxGU3lVbDBBbFRPellSWHFSR1o1U2pXR1RJdmM3UzUydThYOHpJMnlJQyJ9.iRAQA_WZ6-vvAsAnWibbNijEnB4NBF1isZJm6xaizQc"
}


###
POST http://localhost:4000/api/v1.0/routes/add 
Content-Type: application/json

{
    "polygonBody": "33.2425975, 7.8851473, 33.2425975, 7.4931965, 34.5616157, 6.7518965, 35.3969939, 5.3972734, 36.0125357, 4.5216663, 36.9358485, 3.9519409, 38.1229649, 3.2502086, 39.4419831, 3.1624555, 40.8929032, 3.6011423, 42.0800196, 3.7327083, 43.1352341, 4.0834528, 44.4102851, 4.5654736, 45.5534342, 5.0909442, 46.7405506, 6.3589753, 47.7517979, 7.8851473, 47.3560925, 7.7545373,45.9931070, 8.1027386,44.8059906, 8.4506388,43.2231687, 9.7956776,42.6515941, 10.8333060,42.0360523, 11.0490383,41.9920850, 11.4800246,42.3877905, 11.9963384,41.5963795, 13.1115801,40.4092631, 13.9660541,38.9143758, 14.3069695,36.5841103, 13.8380799,36.2323721, 12.8974892,35.8806339, 12.3829283,35.2650921, 12.0393206,35.0452557, 11.3507967,34.9573211, 10.7037917,34.4297139, 10.6174181,34.4297139, 10.0121296,34.2538448, 9.3623528,34.2538448, 8.5375654,33.3744993, 8.4071682,33.2425975, 7.8851473"
    
}
